Vagrant.configure("2") do |config|

    config.vm.hostname = "certificate.vm"
    config.vm.define "certificate"

    config.vm.box = "ubuntu/jammy64"

    config.vm.provider "virtualbox" do |vb|
        vb.name = "certificate"
        vb.memory = 4096
        vb.cpus = 2
    end

    config.vm.network "forwarded_port", guest: 3000, host: 3000

    config.vm.synced_folder ".", "/vagrant", owner: "vagrant", group: "vagrant"

    config.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update && sudo apt-get upgrade -y

        curl -fsSL https://get.docker.com -o get-docker.sh
        sh get-docker.sh

        sudo usermod -aG docker vagrant

        sudo apt-get install -y docker-compose-plugin python3 python3-dev python3-pip

        pip install clickhouse_connect pandas

        sudo systemctl enable docker
        sudo systemctl start docker

        cd /vagrant

        docker compose down
        docker compose build
        docker compose up -d

        SHELL
  end
